mta-service-alerts/config/routes.rb
Rails.application.routes.draw do
  resources :alerts, only: [:index, :show]

end

mta-service-alerts/app/models/alert.rb
require 'open-uri'
require 'date'
require 'pry'

class Alert < ActiveRecord::Base

  def self.get_data

    puts "get data now"

    page = self.download_page
    lines = self.find_lines page

    lines.each do |line|
      line_data = self.line_data line

      if self.alert_exists? line_data
        puts line_data
        current_time = self.convert_time(page.css('timestamp').inner_text)
        self.update_database line_data, current_time
      end
    end
  end

  private

    def self.alert_exists? data
      data[:status] != "GOOD SERVICE"
    end

    def self.download_page
      # For testing purposes, we get a saved serviceData file.
      # return Nokogiri::HTML(open("../research/2015-02-22-08-42-01.xml"))
      url = "http://web.mta.info/status/serviceStatus.txt"
      begin
        page = Nokogiri::HTML(open(url))
      rescue
        puts "Exception #{e}"
        puts "Unable to fetch #{url}"
      end
    end

    def self.find_lines page
      train_names = ["123", "456", "7", "ACE", "BDFM", "G", "JZ", "L", "NQR", "S", "SIR"]
      all_lines = page.css('line')
      all_lines.select do |line|
        train_names.include? line.css('name').inner_text
      end
    end
 
    def self.line_data line
      date = line.css('date').inner_text
      time = line.css('time').inner_text

      result = {
        name: line.css('name').inner_text,
        status: line.css('status').inner_text,
        start_time: "#{date} #{time}",
        text: self.clean_html_page(line)
      }

      unless result[:start_time].blank?
        result[:start_time] = self.convert_time(result[:start_time])
      end

      return result
    end

    def self.clean_html_page line
      regex = /<\/*br\/*>|<\/*b>|<\/*i>|<\/*strong>|<\/*font.*?>|<\/*u>/
      line.css('text').inner_text.gsub(regex, '').gsub('&nbsp;', '')
          .gsub('Posted: ', '').gsub(/\s{2,}/, ' ')
    end

    def self.update_database data, current_time
      line_active_alert = Alert.find_by active: true, name: data[:name]

      if line_active_alert

        if self.same_alert line_active_alert, data
          self.update_end_time line_active_alert, current_time
          # Update the active_until time to current time
        else
          self.set_alert_inactive line_active_alert
          self.create_data data
        end

      else 
        self.create_data data
      end


    end

    def self.same_alert line_active_alert, data
      # binding.pry
        line_active_alert[:status] == data[:status] &&
        line_active_alert[:text] == data[:text]
    end

    def self.set_alert_inactive alert
      alert[:active] = false
      alert.save
    end

    def self.create_data data
      # binding.pry
      alert = Alert.new
      alert[:name] = data[:name]
      alert[:status] = data[:status]
      alert[:start_time] = data[:start_time]
      alert[:end_time] = data[:start_time]
      alert[:text] = data[:text]
      alert[:active] = true

      alert.save
    end

    def self.convert_time time_string
      time_string = time_string.gsub(/\s{2,}/, ' ')
                               .gsub(/0(\d\/)/, '\1')
                               .gsub(/\s+(\d:)/, ' 0\1')

      # AM/PM seems to be broken for strptime
      # This is a hack around that
      if time_string.match('AM')
        DateTime.strptime(time_string, "%m/%d/%Y %l:%M")
      elsif time_string.match('PM')
        DateTime.strptime(time_string, "%m/%d/%Y %l:%M") + 12.hours
      end
    end

    def self.update_end_time record, current_time
      record[:end_time] = current_time
      record.save
    end

end

mta-service-alerts/app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_alert, only: [:show, :edit, :update, :destroy]

  # GET /alerts
  # GET /alerts.json
  def index
    alerts = Alert.all
    render json: alerts
  end

  # GET /alerts/1
  # GET /alerts/1.json
  def show
    alert = alert.find_by({id: params[:id]})
    render json: alert
  end

  # GET /alerts/new
  # def new
  #   @alert = Alert.new
  # end

  # GET /alerts/1/edit
  # def edit
  # end

  # POST /alerts
  # POST /alerts.json
  # def create
  #   @alert = Alert.new(alert_params)

  #   respond_to do |format|
  #     if @alert.save
  #       format.html { redirect_to @alert, notice: 'Alert was successfully created.' }
  #       format.json { render :show, status: :created, location: @alert }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @alert.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /alerts/1
  # PATCH/PUT /alerts/1.json
  # def update
  #   respond_to do |format|
  #     if @alert.update(alert_params)
  #       format.html { redirect_to @alert, notice: 'Alert was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @alert }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @alert.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  # def destroy
  #   @alert.destroy
  #   respond_to do |format|
  #     format.html { redirect_to alerts_url, notice: 'Alert was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = Alert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alert_params
      params[:alert]
    end
end

mta-service-alerts/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

mta-service-alerts/app/helpers/alerts_helper.rb
module AlertsHelper
end

mta-service-alerts/app/helpers/application_helper.rb
module ApplicationHelper
end

mta-service-alerts/app/views/alerts/_form.html.erb
<%= form_for(@alert) do |f| %>
  <% if @alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
      <% @alert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mta-service-alerts/app/views/alerts/edit.html.erb
<h1>Editing Alert</h1>

<%= render 'form' %>

<%= link_to 'Show', @alert %> |
<%= link_to 'Back', alerts_path %>

mta-service-alerts/app/views/alerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Alerts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alerts.each do |alert| %>
      <tr>
        <td><%= link_to 'Show', alert %></td>
        <td><%= link_to 'Edit', edit_alert_path(alert) %></td>
        <td><%= link_to 'Destroy', alert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alert', new_alert_path %>

mta-service-alerts/app/views/alerts/new.html.erb
<h1>New Alert</h1>

<%= render 'form' %>

<%= link_to 'Back', alerts_path %>

mta-service-alerts/app/views/alerts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_alert_path(@alert) %> |
<%= link_to 'Back', alerts_path %>

mta-service-alerts/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MtaServiceAlerts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>